packages:
  - packages/*

catalog:
  '@antfu/eslint-config': ^5.3.0
  '@clack/prompts': ^0.11.0
  '@tsconfig/node22': ^22.0.2
  '@types/ejs': ^3.1.5
  '@types/node': ^22.16.5
  ejs: 3.1.10
  eslint: ^9.31.0
  eslint-plugin-format: ^1.0.1
  eslint-plugin-vue: ~10.3.0
  lint-staged: ^16.1.6
  picocolors: ^1.1.1
  prettier: 3.6.2
  simple-git-hooks: ^2.13.1
  tsdown: ^0.15.1
  typescript: ~5.8.0
