shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - undici-types@6.21.0

packages:
  - packages/*
catalog:
  '@antfu/eslint-config': ^9.3.0
  '@clack/prompts': ^0.11.0
  '@tsconfig/node22': 22.0.5
  '@types/ejs': ^3.1.5
  '@types/node': ^22.20.1
  bumpp: ^10.4.1
  ejs: 3.1.10
  eslint: ^10.9.0
  eslint-plugin-format: ^2.0.1
  eslint-plugin-vue: ^10.10.0
  giget: ^2.0.0
  lint-staged: ^16.4.0
  picocolors: ^1.1.1
  prettier: 3.6.2
  simple-git-hooks: ^2.13.1
  tsdown: ^0.22.14
  typescript: ~6.0.3
