name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    uses: sxzz/workflows/.github/workflows/unit-test.yml@v1
    with:
      skip-test: true
      typecheck: ''
